services:
  web:
    build: .
    ports:
      - 80
    networks:
      - traefik
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-${COMPOSE_PROJECT_NAME}.rule=Host(`${URL}`)"
      - "traefik.http.routers.web-${COMPOSE_PROJECT_NAME}tls=true"
networks:
  traefik:
    external: true